### PR TITLE
Use new `std::io` module

### PR DESCRIPTION
**Pull request by robo9k**
This is a work-in-progress to port the code to the new `std::io` module.

Note that [`std::io`](http://doc.rust-lang.org/std/io/index.html) itself contains the following warning:

> **NOTE**: This module is very much a work in progress and is under active development. At this time it is still recommended to use the `old_io` module while the details of this module shake out.

As such, do not merge until the dust has settled :hand:

### CODE REVIEW

**Comment by jakerr** [comment]
Looking good so far :smile: Thank you for your proactivity in starting this!

**Comment by robo9k** [comment]
Note that the Travis `cargo build` fails due to a `rustc` ICE in `Piston/image`, see https://travis-ci.org/chip8-rust/chip8-ui/builds/50792473#L2697
I did not investigate this any further or reported in anywhere upstream, but I don't think it's a problem with this pull request's code changes.

Edit: So this ICE is already a few days old, see https://github.com/rust-lang/rust/issues/21756#issuecomment-74219656

**Comment by robo9k** [comment]
Rebased onto aa5d470. Now this fails as expected, since chip8-rust/chip8-vm#2 has not been merged after the split.

**Comment by robo9k** [comment]
Even though I've successfully merged the `chip8_vm` part (though no new crate version yet), this pull request here fails to build due to a problem with `rust-sdl2`, so we're a little stuck.

**Comment by robo9k** [comment]
Okay, the issue with `rust-sdl2` is fixed by 9a3a31a. I get a new nasty error about

> SDL not built with haptic (force feedback) support

however `USE=haptic emerge libsdl2` fixed that for now (might be a bug in Gentoo's stable `media-libs/libsdl2`).

**Pull request merged**
